apiVersion: v1
kind: Service
metadata:
  name: {{ include "java-app.fullname" . }}
  labels:
{{ include "java-app.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "java-app.name" . }}
