{{- if .Values.thanos.store.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-store-gateway
  namespace: {{ .Values.namespace }}
  labels:
    app: thanos-store-gateway
spec:
  replicas: {{ .Values.thanos.store.replicas }}
  selector:
    matchLabels:
      app: thanos-store-gateway
      thanos-store-api: "true"
  serviceName: thanos-store-gateway
  template:
    metadata:
      labels:
        app: thanos-store-gateway
        thanos-store-api: "true"
    spec:
      serviceAccountName: monitoring
      containers:
        - name: thanos
          image: {{ .Values.thanos.image }}
          args:
          - store
          - --grpc-address=0.0.0.0:10901
          - --http-address=0.0.0.0:10902
          - --data-dir=/data
          - "--objstore.config={type: S3, config: {bucket: '{{.Values.thanos.archive_bucket}}', endpoint: '{{.Values.thanos.endpoint}}', region: '{{.Values.thanos.region}}'}}"
          ports:
          - name: http
            containerPort: 10902
          - name: grpc
            containerPort: 10901
          resources:
            {{- toYaml .Values.thanos.store.resources | nindent 12 }}
          livenessProbe:
            failureThreshold: 4
            httpGet:
              path: /-/healthy
              port: 10902
              scheme: HTTP
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 10902
              scheme: HTTP
          terminationMessagePolicy: FallbackToLogsOnError
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-store-gateway
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: grpc
      port: 10901
      targetPort: grpc
  selector:
    thanos-store-api: "true"
{{- end }}
